/*!
 * jQuery UI Widget 1.8.4
 *
 * Copyright 2010, AUTHORS.txt (http://jqueryui.com/about)
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * http://docs.jquery.com/UI/Widget
 */
(function(b,c){var a=b.fn.remove;b.fn.remove=function(d,e){return this.each(function(){if(!e){if(!d||b.filter(d,[this]).length){b("*",this).add([this]).each(function(){b(this).triggerHandler("remove")})}}return a.call(b(this),d,e)})};b.widget=function(e,g,d){var f=e.split(".")[0],i;e=e.split(".")[1];i=f+"-"+e;if(!d){d=g;g=b.Widget}b.expr[":"][i]=function(j){return !!b.data(j,e)};b[f]=b[f]||{};b[f][e]=function(j,k){if(arguments.length){this._createWidget(j,k)}};var h=new g();h.options=b.extend(true,{},h.options);b[f][e].prototype=b.extend(true,h,{namespace:f,widgetName:e,widgetEventPrefix:b[f][e].prototype.widgetEventPrefix||e,widgetBaseClass:i},d);b.widget.bridge(e,b[f][e])};b.widget.bridge=function(e,d){b.fn[e]=function(h){var f=typeof h==="string",g=Array.prototype.slice.call(arguments,1),i=this;h=!f&&g.length?b.extend.apply(null,[true,h].concat(g)):h;if(f&&h.substring(0,1)==="_"){return i}if(f){this.each(function(){var j=b.data(this,e),k=j&&b.isFunction(j[h])?j[h].apply(j,g):j;if(k!==j&&k!==c){i=k;return false}})}else{this.each(function(){var j=b.data(this,e);if(j){if(h){j.option(h)}j._init()}else{b.data(this,e,new d(h,this))}})}return i}};b.Widget=function(d,e){if(arguments.length){this._createWidget(d,e)}};b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(e,f){b.data(f,this.widgetName,this);this.element=b(f);this.options=b.extend(true,{},this.options,b.metadata&&b.metadata.get(f)[this.widgetName],e);var d=this;this.element.bind("remove."+this.widgetName,function(){d.destroy()});this._create();this._init()},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},widget:function(){return this.element},option:function(f,g){var e=f,d=this;if(arguments.length===0){return b.extend({},d.options)}if(typeof f==="string"){if(g===c){return this.options[f]}e={};e[f]=g}b.each(e,function(h,i){d._setOption(h,i)});return d},_setOption:function(d,e){this.options[d]=e;if(d==="disabled"){this.widget()[e?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",e)}return this},enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(e,f,g){var j=this.options[e];f=b.Event(f);f.type=(e===this.widgetEventPrefix?e:this.widgetEventPrefix+e).toLowerCase();g=g||{};if(f.originalEvent){for(var d=b.event.props.length,h;d;){h=b.event.props[--d];f[h]=f.originalEvent[h]}}this.element.trigger(f,g);return !(b.isFunction(j)&&j.call(this.element[0],f,g)===false||f.isDefaultPrevented())}}})(jQuery);